### ISSUE TITLE
how to receive the digest message send from DP in tofino asic

### ISSUE THREAD

**Issue by hanyifansuda** [DINGDAMU/INDDoS#1]
I noticed that you only provided an INDDoS code that can run in the tofino asic, but did not introduce how to use python scripts on the control plane (bfshell) to collect digest information sent from DP. Please tell me how to write such a script. Looking forward to your reply, thank you.

**Comment by DINGDAMU** [comment]
I am not sure if I can disclose the answer in public due to NDA. You can search "Few questions about digest" in  [Intel® Connectivity Research Program (Private)](https://community.intel.com/t5/Intel-Connectivity-Research/gh-p/connectivity-research-program), then you'll get the answer.
